/**
 *
  buttons: Button[];
  promoAd: PromoAd;
  relatedTags: RelatedTag[];

  heroVideo: HeroVideo[];
  heroVideoMobile: HeroVideo[];
  subtitle: string;
  roles: Role[];
  difficulty: string;
  difficultyLevel: string;
  abilities: Ability[];
 */

export type ChampionMap = Map<string, Champion>;

// Generated by https://quicktype.io

export interface Champion {
  name: string;
  image: string;
  squareImage: string;
}

// export interface Image {
//   url: string;
//   title: string;
// }

// export interface Role {
//   name: string;
//   icon: Image;
//   machineName: string;
// }

// export interface URL {
//   url: string;
// }
